name: Run API Tests

on: [push, pull_request]  # trigger

jobs:
  test:
    runs-on: ubuntu-latest  # environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run API tests
        run: python tests/test_api.py  # run tests