name: CI/CD Pipeline

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start API Server
        run: |
          nohup uvicorn app:app --host 127.0.0.1 --port 8000 > api.log 2>&1 &
          sleep 10
          
      - name: Check if API is running
        run: curl --retry 5 --retry-delay 5 --max-time 10 --retry-connrefused http://127.0.0.1:8000/health

      - name: Run tests
        run: pytest tests/
